---
source:
  urn: li:dataPlatform:hive
database: logging_events
table: fct_users_created
owners:
  - urn:li:corpuser:jdoe
  - urn:li:corpuser:datahub
tags: []
columns:
  - name: user_id
    type: varchar(100)
  - name: user_name
    type: boolean
upstream_lineage:
  - urn:li:dataset:(urn:li:dataPlatform:hive,logging_events,PROD)